- title: "Study of microbiota-host interaction by exposure to gliadin in an animal model of *Caenorhabditis elegans*"
# Ongoing Projects
# TODO: Add image for each project
# Symbology:
  # Ongoing projects:
    # 0: Research incubator Ongoing project
    # 1: Research group BMTE Ongoing project (Lines of research)

  key: "BIO2025-SMH"
  ongoing: 1 
  researchers: "*Hillary Patarroyo Sánchez*, *Elpidia Poveda*, *Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "This work focuses on understanding the effect of exposure to gliadin in the context of microbiota-host interaction using the Caenorhabditis elegans animal model, which has around 40% of predicted proteins that have homologs in humans, and morphological similarity given by the actin-rich microvellosities on the apical side of the intestinal epithelium cells where the absorption of nutrients occurs."


- title: "Characterization of an unknown pathogen of the brownish alga *Lobophora J. Agardh* in reef environments of the Seaflower Biosphere Reserve."
  key: "BIO2025-CUP"
  ongoing: 1 
  researchers: "*Santiago Alberto Santos*, *Brigitte Gavio*, *Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "The health of marine macroalgae is closely linked to the health of the oceans, which impacts the resilience of reefs. The brownish alga Lobophora (Dictyotales, Phaeophyceae) plays a key role in reef ecosystems as a benthic primary producer."

- title: "Exploring bacterial secreted proteins and small RNAs in *Caenorhabditis elegans*: A computational and imaging approach to animal-microbiota interactions"
  key: "BIO2025-EBS"
  ongoing: 1 
  researchers: "*Jose Luis Maldonado Gutiérrez*, *Kevin Manolo Forero Nova*, *Santiago Cortes Camargo* ,*Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "*Caenorhabditis elegans* is a widely used model organism in biology due to its ability to provide information on key molecular processes, including host-microbiota interactions."

- title: "Identification and evaluation of the sRNA regulatory network in the fast-growing bacterium *Vibrio natriegens*"
  key: "BIO2025-IEsRNA"
  ongoing: 1 
  researchers: "*Valentina Flórez Tellez*, *Daniel Schindler (MPI Terrestrial Microbiology)*, *Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "The bacterium *Vibrio natriegens* is known for having the fastest documented growth rate, with 10 minute duplication time. Due to its rapid growth rate and halophilic nature, *V. natriegens* is of general interest to biotechnology."


- title: "Characterization of gluten degradation potential in human intestinal bacteria by analysis of *prolyl-oligopeptidase* domain architectures"
  key: "BIO2025-CGD"
  ongoing: 1 
  researchers: "*Édisson Leandro Robles Sánchez*, *Hillary Patarroyo Sánchez*, *Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "This project seeks to identify culturable intestinal bacteria of human origin with gluten-degrading potential by analyzing the domain architectures of prolyl-oligopeptidases (bPOPs)."

- title: "Comparison of the methabolic profile in defined medium of the wild type strain *Vibrio natriegens* and a strain with rationally fusioned chromosomes"
  key: "BIO2025-CMP"
  ongoing: 0 
  researchers: "*Angelica Millan Aldana*, *Maryam Chaib De Mares*, *Daniel Schindler (MPI Terrestrial Microbiology)*" # Researchers involved in the project
  selected: 1
  summary: "*Vibrio natriegens* is emerging as a potential host for biotechnology, mainly due to its remarkable intrinsic properties such as exceptional growth rates and versatile metabolites. Although recent studies have highlighted the potential of *V. natriegens* for biotechnological applications, a deeper understanding of its metabolism and regulation is needed to fully exploit its potential. This study focuses on characterising the metabolome and establishing growth conditions for V. natriegens in defined media."


- title: "Design of a Metabolic Model for the Production of *Tropane Alkaloids"
  key: "BIO2025-DMM"
  ongoing: 0 
  researchers: "*Julieth Camila Naranjo*, *Maryam Chaib De Mares*" # Researchers involved in the project
  selected: 1
  summary: "Tropane alkaloids (TAs) are essential compounds in medicine, used to treat various conditions. However, their current production through solanaceous plant cultivation faces significant limitations, such as the complexity and cost of chemical synthesis, dependence on agriculture, and negative environmental impact."

- title: "Carbohydrate-active enzymes from the gut microbiota of the herbivore Coendou vestitus and heterologous expression in Bacillus subtilis for the degradation of recalcitrant plant biomass"
  key: "BIO2025-CAE"
  ongoing: 0 
  researchers: "*Diego Enrique Carrillo Ruíz*, *Maryam Chaib De Mares*, *Daniel Fernando Rojas Tapias (Agrosavia)*" # Researchers involved in the project
  selected: 1
  summary: "The use of microbial consortia in the degradation of recalcitrant plant material has been proposed as a naturally occurring alternative to increasing the saccharification efficiency of lignocellulosic biomass. This work consists of characterizing the carbohydrate-active enzymes present in the feces of the porcupine *Coendou vestitus*, a herbivore whose diet is primarily plant-based."

